name: frontend
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.3.6
  http: ^0.13.6 # HTTP package for API requests
  shared_preferences: ^2.2.0 # SharedPreferences for storing tokens

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/splash_logo.jpg

flutter_native_splash:
  color: "#ffffff"  # Background color (white)
  image: assets/splash_logo.jpg  # Path to your splash image
  android: true
  ios: true
  fullscreen: true
