name: frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.3.6
  intl_phone_field: ^3.1.0
  shared_preferences: ^2.0.6
  http: ^0.13.3
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.jpg

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_logo.jpg
  android_12:
    image: assets/splash_logo.jpg
  fullscreen: true

  dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.0
