name: frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  intl_phone_field: ^3.1.0
  shared_preferences: ^2.0.6
  http: ^1.3.0
  dio: ^5.0.0
  http_certificate_pinning: ^3.0.0
  intl: ^0.20.2 # Check for latest version



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.png

flutter_native_splash:
  color: "#000000"
  image: assets/splash_logo.png
  android_12:
    image: assets/splash_logo.png
  fullscreen: true

